export const PLATFORMS = [
  {
    id: 'ebay',
    name: 'eBay',
    color: '#e53238',
    bgColor: 'bg-red-50',
    textColor: 'text-red-600',
    borderColor: 'border-red-200',
    hint: 'Best for electronics, sneakers, collectibles',
    icon: 'EB',
  },
  {
    id: 'depop',
    name: 'Depop',
    color: '#ff2300',
    bgColor: 'bg-pink-50',
    textColor: 'text-pink-600',
    borderColor: 'border-pink-200',
    hint: 'Best for streetwear, vintage, Y2K',
    icon: 'DP',
  },
  {
    id: 'poshmark',
    name: 'Poshmark',
    color: '#820f7e',
    bgColor: 'bg-fuchsia-50',
    textColor: 'text-fuchsia-700',
    borderColor: 'border-fuchsia-200',
    hint: 'Best for brands, designer, clothes',
    icon: 'PM',
  },
]

export function getPlatform(id) {
  return PLATFORMS.find((p) => p.id === id)
}

export function buildExportText(listing, platform) {
  const p = getPlatform(platform)
  const lines = [
    `--- RESELLAI Export for ${p?.name || platform} ---`,
    '',
    `TITLE:`,
    listing.title,
    '',
    `PRICE: $${Number(listing.price).toFixed(2)}`,
    listing.priceRange ? `(AI suggested range: $${listing.priceRange.low}–$${listing.priceRange.high})` : '',
    `CONDITION: ${listing.condition}`,
    `CATEGORY: ${listing.category}`,
    '',
    `DESCRIPTION:`,
    listing.description,
  ]

  if (listing.notes?.length > 0) {
    lines.push('')
    lines.push('--- SELLER NOTES (verify before posting) ---')
    listing.notes.forEach((note) => lines.push(`• ${note}`))
  }

  if (listing.requiresReview) {
    lines.push('')
    lines.push(`⚠ AI CONFIDENCE: ${listing.confidence?.toUpperCase() || 'UNKNOWN'}`)
    lines.push('This listing should be reviewed before posting.')
  }

  lines.push('')
  lines.push('--- Generated by RESELLAI (mock export) ---')

  return lines.filter((l) => l !== undefined).join('\n')
}

export async function copyToClipboard(text) {
  if (navigator.clipboard && window.isSecureContext) {
    await navigator.clipboard.writeText(text)
    return true
  }
  const ta = document.createElement('textarea')
  ta.value = text
  ta.style.position = 'fixed'
  ta.style.opacity = '0'
  document.body.appendChild(ta)
  ta.select()
  const ok = document.execCommand('copy')
  document.body.removeChild(ta)
  return ok
}
